---
- name: Install tomcat
  hosts: servers
  become: true
  tasks:
   - name: Download tomcat 
     get_url:
       url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz
       dest: /usr/local
      
   - name: Extract Packages
     unarchive:
       src: /usr/local/apache-tomcat-8.5.58.tar.gz
       dest: /usr/local
       remote_src: yes
      
   - name: Copy War file to tomcat 
     copy:
       src: ./
       dest: /usr/local/webapps/
      
   - name: Start tomcat
     shell: nohup /usr/local/apache-tomcat-8.5.46/bin/startup.sh
   
   
    
    
  

